#!/bin/sh

set -e

case "$1" in
  configure)
    # Update module dependencies
    depmod -a
    # Update initramfs
    update-initramfs -u
    # Update library cache 
    echo "/usr/loca/bin" > /etc/ld.so.conf.d/qat.conf
    ldconfig
    # Update configuration
    echo "# blacklist qat_dh895xccvf" > /etc/modprobe.d/blacklist-qat-vfs.conf
    # Update service
    # systemctl reload-daemon
    ;;
esac

exit 0

